pointcloud_channel_fusions:
  rgb: 'color'
  default: 'average'

image_channel_fusions:
  rgb: 'color'
  default: 'exponential'
  feat_.*: 'exponential'

subscribers:
  depth_cam:
    topic_name: '/camera/depth/image_raw'
    camera_info_topic_name: '/camera/depth/camera_info'
    data_type: depth
  # depth_cam:
  #   topic_name: '/camera/depth/depth_to_cloud'
  #   data_type: pointcloud
  # lidar:
  #   topic_name: '/scan_to_cloud'
  #   data_type: pointcloud
  # color_cam: # for color camera
  #   topic_name: '/camera/rgb/image_raw'
  #   camera_info_topic_name: '/camera/depth/camera_info'
  #   data_type: image
  # front_cam:
  #   topic_name: '/camera/depth/points'
  #   data_type: pointcloud

publishers:
  elevation_map_raw:
    layers: ['elevation', 'rgb']
    basic_layers: ['elevation']
    fps: 5.0
