pointcloud_channel_fusions:
  rgb: 'color'
  default: 'average'

image_channel_fusions:
  rgb: 'color'
  default: 'exponential'
  feat_.*: 'exponential'

subscribers:
  depth_cam:
    topic_name: '/cliff_gemini2/depth/image_raw'
    camera_info_topic_name: '/cliff_gemini2/depth/camera_info'
    data_type: depth
  # color_cam: # for color camera
  #   topic_name: '/camera/rgb/image_raw'
  #   camera_info_topic_name: '/camera/depth/camera_info'
  #   data_type: image

publishers:
  elevation_map_raw:
    layers: ['elevation']
    basic_layers: ['elevation']
    fps: 5.0
